version: '2'
services:
  ml-boilerplate:
    container_name: ml-boilerplate
    image: jupyter/tensorflow-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks/:/home/jovyan/work/:z
      - ./jupyter_notebook_config.py/:/home/jovyan/.jupyter/jupyter_notebook_config.py
